### ISSUE TITLE
"ps -p <zombie-pid>" returns nothing on FreeBSD

### ISSUE THREAD

**Issue by svmhdvn** [google/capsicum-test#18]
`Pdfork.Simple` fails on FreeBSD because `ProcessState(<zombie-pid>)` returns nothing. As a temporary workaround, #17 changes `ProcessState(...)` to use `ps -a -p <zombie-pid>`. This should be removed when FreeBSD reports zombie processes with `sysctl kern.proc.pid.<pid>`.

**Comment by ngie-eign** [comment]
It does report this information on 13.0-CURRENT:
```
$ uname -a
FreeBSD pinklady-fbsd-current.local 13.0-CURRENT FreeBSD 13.0-CURRENT r342974+4e929336206c(googletest-integration) GENERIC-NODEBUG  amd64
$ ps -a -p 42972                                                                                                                                                             
  PID TT  STAT    TIME COMMAND
42972  3  Z+   0:00.00 <defunct>
```

**Comment by emaste** [comment]
Does the test pass now with #17 reverted?

**Comment by ngie-eign** [comment]
> Does the test pass now with #17 reverted?

Yes. I'm going to send out a PR with this and some other changes to fix the test run on FreeBSD.

**Comment by ngie-eign** [comment]
@svmhdvn: could you please close this PR since the test passes on dev with FreeBSD 13.0-CURRENT?

**Comment by svmhdvn** [comment]
Yes, closing now.
