### ISSUE TITLE
Check the value of kern.trap_enotcap when running on FreeBSD

### ISSUE THREAD

**Issue by markjdb** [google/capsicum-test#23]
I left kern.trap_enotcap set to 1 while doing some capsicum-related work. This causes many of the capsicum tests to fail; it would be nice if the suite verified that the sysctl is set to 0 as a precondition.

**Comment by daviddrysdale** [comment]
What rough fraction of the tests still worked with trap_enotcap==1 ?   (If the majority fail, it might be easiest to just disable the whole test process; if it's only a few, we could maybe add something analogous to the `REQUIRE_ROOT()` macro to the relevant tests.)

**Comment by markjdb** [comment]
Almost a third of the tests fail. I think it would be reasonable to just disable the whole test in that case; that setting makes it impractical to verify ENOTCAPABLE errors.

[  FAILED  ] 26 tests, listed below:
[  FAILED  ] Capability.BasicInterceptionForked
[  FAILED  ] Capability.OpenAtDirectoryTraversalForked
[  FAILED  ] Capability.InheritanceForked
[  FAILED  ] Capability.MmapForked
[  FAILED  ] Capability.OperationsForked
[  FAILED  ] Capability.DirOperationsForked
[  FAILED  ] Capability.SocketTransferForked
[  FAILED  ] ForkedExecve_InCapMode._
[  FAILED  ] ForkedExecve_FailWithoutCap._
[  FAILED  ] ForkedExecve_SucceedWithCap._
[  FAILED  ] Fexecve.ExecveFailureForked
[  FAILED  ] Fexecve.CapModeScriptFailForked
[  FAILED  ] Pdfork.OtherUserForked
[  FAILED  ] PipePdfork.Close
[  FAILED  ] PipePdforkDaemon.NoPDSigchld
[  FAILED  ] ForkedWithFiles_DisallowedFileSyscalls._
[  FAILED  ] ForkedWithFiles_DisallowedSocketSyscalls._
[  FAILED  ] Capmode.AllowedAtSyscallsCwd
[  FAILED  ] Capmode.NewThreadForked
[  FAILED  ] Capmode.SelfKillForked
[  FAILED  ] ForkedWithFiles_AllowedMiscSyscalls._
[  FAILED  ] Fcntl.BasicForked
[  FAILED  ] Openat.RelativeForked
[  FAILED  ] ForkedOpenatTest_InCapabilityMode._
[  FAILED  ] Select.LotsOFileDescriptorsForked
[  FAILED  ] RenameAt.AbsDesignationSame

**Comment by daviddrysdale** [comment]
OK, turning everything off sounds reasonable.  Any chance of a PR?  (I don't have a FreeBSD 11 system close to hand...)

**Comment by markjdb** [comment]
I'll add it to my todo list. There's a small handful of failures in the suite on FreeBSD-CURRENT which I still need to investigate. I'm interested in integrating this test suite into the FreeBSD base system, so I'll deal with all of this issue as a part of that.

**Comment by ngie-eign** [comment]
@markjdb: #42 will address this issue.

**Comment by ngie-eign** [comment]
This issue can be closed.

**Comment by daviddrysdale** [comment]
Fixed by #42
