### ISSUE TITLE
Build fails on FreeBSD stable/10 due to lack of x32 support

### ISSUE THREAD

**Issue by emaste** [google/capsicum-test#8]
```
feynman% gmake
cc -m64 -Wall -g -mx32 -static -o mini-me.x32 mini-me.c
cc: error: unknown argument: '-mx32'
GNUmakefile:64: recipe for target 'mini-me.x32' failed
gmake: *** [mini-me.x32] Error 1
```

Need to avoid adding mini-me.x32 to EXTRA_PROGS when the compiler does not support -mx32

**Comment by daviddrysdale** [comment]
Ah, there's a bigger problem -- I was using `GNUmakefile` vs. `makefile` as a quick and dirty Linux/FreeBSD discriminator, on the assumption that a FreeBSD build would use non-GNU make.

If you need gmake support for FreeBSD too, then I'll have to do something more sophisticated (but hopefully without going full autoconf on it...)

**Comment by emaste** [comment]
Ah, right you are - I'm not sure why I ended up using GNU make now. I'll close this; we'll presumably revisit when Capsicum makes it to other operating systems.
